const COLORS=[['coral','#d95b4b'],['blue','#397a9b'],['gold','#d69b2d'],['violet','#806299']];
const N=7, DIRS=[[0,-1],[1,0],[0,1],[-1,0]], DICe=[1,2,2,3,3,4];
let S={}; const $=s=>document.querySelector(s);
function newGame(){const count=+$('#playerCount').value, ai=$('#aiEnabled').checked;S={players:COLORS.slice(0,count).map(([name,color],i)=>({name:['산호','파랑','황금','보라'][i],color,money:30,rugs:count===4?12:15,ai:ai&&i===1})),board:Array.from({length:N},()=>Array(N).fill(null)),assam:{x:3,y:3,dir:0},turn:0,phase:'turn',choice:0,logs:['카펫 시장이 문을 열었습니다.'],over:false};$('#setup').classList.add('hidden');$('#game').classList.remove('hidden');render()}
function current(){return S.players[S.turn]}
function log(t){S.logs.unshift(t);S.logs=S.logs.slice(0,7)}
// Edge pairing tables: index = lane (column for top/bottom, row for left/right),
// value = the lane it connects to. Top & Left: (0,1)(2,3)(4,5) swap, lane 6 self-loops.
// Bottom & Right: lane 0 self-loops, (1,2)(3,4)(5,6) swap. Matches the arch mosaics
// printed on the physical board (A1<->B1, C1<->D1, E1<->F1, G1 self; A1<->A2, A3<->A4,
// A5<->A6, A7 self; B7<->C7, D7<->E7, F7<->G7, A7 self; G2<->G3, G4<->G5, G6<->G7, G1 self).
const TOP_PAIR=[1,0,3,2,5,4,6], LEFT_PAIR=[1,0,3,2,5,4,6];
const BOTTOM_PAIR=[0,2,1,4,3,6,5], RIGHT_PAIR=[0,2,1,4,3,6,5];
function step(){let {x,y,dir}=S.assam;let [dx,dy]=DIRS[dir];let nx=x+dx,ny=y+dy;if(nx>=0&&nx<N&&ny>=0&&ny<N)return{x:nx,y:ny,dir};
 // Board edge: Assam follows the arch mosaic printed there, swapping into the linked lane
 // and reversing direction - except at the four "self" corners (G1 and A7, each seen from
 // both of their edges), where the mosaic turns him 90 deg along the border instead: he
 // stays on the same square and continues along the edge he just reached, rather than
 // bouncing back into the grid. Leaving the board doesn't use up a movement point, so this
 // step both re-enters and turns him.
 if(dir===0)return x===N-1?{x,y:0,dir:3}:{x:TOP_PAIR[x],y:0,dir:2};
 if(dir===2)return x===0?{x,y:N-1,dir:1}:{x:BOTTOM_PAIR[x],y:N-1,dir:0};
 if(dir===1)return y===0?{x:N-1,y,dir:2}:{x:N-1,y:RIGHT_PAIR[y],dir:3};
 return y===N-1?{x:0,y,dir:0}:{x:0,y:LEFT_PAIR[y],dir:1};}
function connected(x,y,owner){let seen=new Set,stack=[[x,y]];while(stack.length){let[a,b]=stack.pop(),k=a+','+b;if(seen.has(k)||a<0||a>=N||b<0||b>=N||S.board[b][a]!==owner)continue;seen.add(k);DIRS.forEach(([dx,dy])=>stack.push([a+dx,b+dy]))}return seen.size}
function roll(){S.assam.dir=(S.assam.dir+S.choice+4)%4;let d=DICe[Math.floor(Math.random()*DICe.length)];for(let i=0;i<d;i++)S.assam=step();let owner=S.board[S.assam.y][S.assam.x];let msg=`${current().name} 상인이 ${d}칸 이동했습니다.`;if(owner!==null&&owner!==S.turn){let fee=Math.min(current().money,connected(S.assam.x,S.assam.y,owner));current().money-=fee;S.players[owner].money+=fee;msg+=` ${S.players[owner].name}에게 ${fee} 디르함을 지불합니다.`}log(msg);S.phase='place';render();if(current().ai)setTimeout(aiPlace,650)}
function validPlacements(){let out=[];let{x,y}=S.assam;for(let yy=0;yy<N;yy++)for(let xx=0;xx<N;xx++){if(Math.abs(xx-x)+Math.abs(yy-y)!==1)continue;for(const[dx,dy]of [[1,0],[0,1]]){let b=[xx+dx,yy+dy];if(b[0]>=N||b[1]>=N)continue;let vals=[S.board[yy][xx],S.board[b[1]][b[0]]];if(vals[0]!==null&&vals[0]===vals[1]&&vals[0]!==S.turn)continue;out.push([[xx,yy],b])}}return out}
function place(a,b){if(S.phase!=='place'||current().rugs<=0)return;S.board[a[1]][a[0]]=S.turn;S.board[b[1]][b[0]]=S.turn;current().rugs--;log(`${current().name} 상인이 카펫을 펼쳤습니다.`);if(S.players.every(p=>p.rugs===0)){finish();return}S.turn=(S.turn+1)%S.players.length;S.phase='turn';S.choice=0;render();if(current().ai)setTimeout(aiTurn,700)}
function finish(){S.over=true;let visible=S.players.map((p,i)=>S.board.flat().filter(v=>v===i).length);S.players.forEach((p,i)=>p.score=p.money+visible[i]);let best=Math.max(...S.players.map(p=>p.score));log(`게임 종료 — ${S.players.filter(p=>p.score===best).map(p=>p.name).join(', ')} 승리!`);render()}
function aiTurn(){if(S.phase!=='turn')return;S.choice=[-1,0,1][Math.floor(Math.random()*3)];roll()};function aiPlace(){let v=validPlacements();if(v.length)place(...v[Math.floor(Math.random()*v.length)])}
function render(){let p=current();$('#players').innerHTML=S.players.map((x,i)=>`<div class="player ${i===S.turn&&!S.over?'active':''}" style="--p:${x.color}"><div class="player-name"><i class="swatch"></i>${x.name}${x.ai?' · AI':''}</div><div class="stats">${x.money} D · 카펫 ${x.rugs}${S.over?` · ${x.score}점`:''}</div></div>`).join('');$('#turnTitle').textContent=S.over?'시장이 문을 닫았습니다':`${p.name} 상인의 차례`;$('#phaseText').textContent=S.over?'FINAL SCORE':S.phase==='turn'?'1 · 방향과 주사위':'2 · 카펫 배치';let valid=S.phase==='place'?validPlacements():[];let set=new Set(valid.flat().map(c=>c.join(',')));$('#board').innerHTML='';for(let y=0;y<N;y++)for(let x=0;x<N;x++){let c=document.createElement('div');c.className='cell';let v=S.board[y][x];if(v!==null)c.innerHTML=`<div class="rug" style="--rug:${S.players[v].color}"></div>`;if(set.has(x+','+y)){c.classList.add('valid');let pair=valid.find(z=>z[0][0]===x&&z[0][1]===y||z[1][0]===x&&z[1][1]===y);c.onclick=()=>place(...pair)}if(x===S.assam.x&&y===S.assam.y){let a=document.createElement('div');a.className='assam';a.style.transform=`rotate(${S.assam.dir*90}deg)`;c.append(a)}$('#board').append(c)}$('#events').innerHTML=S.logs.map(x=>`<div class="event">${x}</div>`).join('');if(S.over){$('#actions').innerHTML='<p class="status">점수 = 보이는 카펫 칸 + 디르함. 새 게임을 시작해 보세요.</p>';return}if(S.phase==='turn'){$('#actions').innerHTML=`<div class="action-row"><p class="status">아삼의 방향을 고른 뒤 굴리세요.</p><button class="turn-btn ${S.choice===-1?'selected':''}" data-d="-1">↶ 왼쪽</button><button class="turn-btn ${S.choice===0?'selected':''}" data-d="0">↑ 직진</button><button class="turn-btn ${S.choice===1?'selected':''}" data-d="1">오른쪽 ↷</button><button class="primary" id="roll">주사위 굴리기</button></div>`;document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{S.choice=+b.dataset.d;render()});$('#roll').onclick=roll}else $('#actions').innerHTML='<p class="status">아삼과 변을 맞댄 흰 테두리 칸을 눌러 2칸짜리 카펫을 놓으세요.</p>'}
$('#startBtn').onclick=newGame;$('#helpBtn').onclick=()=>{$('#modalContent').innerHTML='<div class="rules"><h2>게임 방법</h2><ol><li>아삼을 직진·왼쪽·오른쪽 중 하나로 돌리고 주사위를 굴립니다. 가장자리에서는 시장의 U턴 길을 따라 이동합니다.</li><li>상대 카펫 위에 멈추면, 그 칸과 변으로 이어진 같은 색 카펫 칸 수만큼 디르함을 냅니다.</li><li>아삼에 인접한 두 칸에 내 카펫을 둡니다. 한 장으로 상대 카펫 한 장을 완전히 덮을 수는 없습니다.</li><li>카펫이 모두 소진되면 보이는 카펫 칸 + 보유 디르함이 점수입니다.</li></ol><p class="status">원작: Dominique Ehrhard · 비공식 디지털 구현</p></div>';$('#modal').showModal()};$('#closeModal').onclick=()=>$('#modal').close();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
